### ISSUE TITLE
smtp server crashed but process keeps running

### ISSUE THREAD

**Issue by electron0zero** [grafana/smtprelay#8]
need to investigate, stacktrace:
```
2021/02/03 15:20:33 loading config...
2021/02/03 15:20:33 remote_pass not set, try REMOTE_PASS env var
2021/02/03 15:20:33 found data in REMOTE_PASS env var
2021/02/03 15:20:33 starting smtprelay, version: 1.4.0
2021/02/03 15:20:33 Listen on 0.0.0.0:2525 ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x56e646]

goroutine 11 [running]:
net.networkNumberAndMask(0x0, 0x486a31, 0x6ca160, 0x1, 0x1, 0xc000064d70, 0x0)
	/snap/go/6745/src/net/ip.go:476 +0x26
net.(*IPNet).Contains(0x0, 0xc00001e360, 0x10, 0x10, 0x0)
	/snap/go/6745/src/net/ip.go:500 +0x2f
main.connectionChecker(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffcbe5c49e4, 0x9, ...)
	/home/suraj/wd/grafana/smtprelay/main.go:37 +0x185
github.com/chrj/smtpd.(*session).welcome(0xc000012420)
	/home/suraj/go/pkg/mod/github.com/chrj/smtpd@v0.2.0/smtpd.go:285 +0xe2
github.com/chrj/smtpd.(*session).serve(0xc000012420)
	/home/suraj/go/pkg/mod/github.com/chrj/smtpd@v0.2.0/smtpd.go:239 +0x358
github.com/chrj/smtpd.(*Server).Serve.func1(0xc000010048, 0xc000012420)
	/home/suraj/go/pkg/mod/github.com/chrj/smtpd@v0.2.0/smtpd.go:180 +0x4d
created by github.com/chrj/smtpd.(*Server).Serve
	/home/suraj/go/pkg/mod/github.com/chrj/smtpd@v0.2.0/smtpd.go:177 +0x193
```

this loop can be possible reason: https://github.com/grafana/smtprelay/blob/4ca35c10b60612fd4792f746f54354d6ccef10d8/main.go#L296

it was running on k8s, and pod was alive:
`smtprelay-66d87ff4cb-glg8l              1/1     Running       0          51m`

**Comment by electron0zero** [comment]
could not reproduce this, will reopen If we see it again
